#!/bin/bash

[ -d Java ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f Java/Parse.class ] || {
    echo "Java/Parse.class missing" >&2
    exit 2
}

if [ "$1" = "-j" ] 
then
    jar=$2
    shift
    shift
fi

if [ -n "$jar" ]
then
       (java -cp ${jar}:./Java Parse $*)
else
        (java -cp ./Java Parse $*)
fi

