#!/bin/bash

[ -d "${PWD}/Java" ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f "${PWD}/Java/Rep.class" ] || {
    echo "Java/Rep.class missing" >&2
    exit 2
}

if [ "$1" = "-j" ] 
then
    jar=$2
    shift
    shift
fi

java -cp ${jar}:./Java Rep $*

