#!/bin/bash

[ -d Java ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f Java/Rep.class ] || {
    echo "Java/Rep.class missing" >&2
    exit 2
}

if [ "$1" = "-j" ] 
then
    jar=$2
    shift
    shift
fi

if [ -n "$jar" ]
then
       (java -cp ${jar}:./Java Rep -t)
else
        (java -cp ./Java Rep -t)
fi

