#!/bin/bash

[ -d Java ] || {
    echo "Java directory missing" >&2
    exit 1
}

[ -f Java/Scan.class ] || {
    echo "Java/Scan.class missing" >&2
    exit 2
}

if [ "$1" = "-j" ] 
then
    jar=$2
    shift
    shift
fi

java -cp ${jar}:./Java Scan
